config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'application#search', :as => 'search_page'
  get '/most_follows' => 'application#most_follows', :as => 'most_follows'
  get '/most_recent', to: 'posts#most_recent', as: 'recent'
  get '/users/:id/followers' => 'follows#followers'
  get '/users/:id/following' => 'follows#followees'
  post '/users/:id/follow_user' => 'follows#follow_user'
  post '/users/:id/unfollow_user' => 'follows#unfollow_user'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    

  resources :users, only: [:index, :show]
  resources :posts do
    resources :comments
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#welcome'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :content, length: { maximum: 250 }, presence: true


    belongs_to :post
    belongs_to :author, class_name: 'User', foreign_key: :author_id

    default_scope { order(created_at: :desc)}
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: 'User'
    belongs_to :followee, class_name: 'User'
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, length: { maximum: 100 }, presence: true


    belongs_to :user
    has_many :comments
    has_one_attached :image

    default_scope { order(created_at: :desc)}
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :posts
  has_many :comments, foreign_key: :author_id, class_name: "Comment"
  has_many :commented_posts, through: :comments, source: :author
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

      devise :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end 
  end

  def follow(user_id)
    followed_users.create(followee_id: user_id)
  end

  def unfollow(user_id)
    followed_users.find_by(followee_id: user_id).destroy
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    def welcome
        
    end

    def search
        if params[:search].blank?  
            redirect_to(posts_path, alert: "Empty field!") and return  
        else  
            @parameter = params[:search].downcase  
            @results = Post.all.where("lower(content) LIKE :search", search: @parameter)
        end 
    end

    def most_follows
        @user = current_user
        @users = User.all
        @user_most_follows = @users.sort_by {|user| user.followers.count}.last
    end


    protected

    def configure_permitted_parameters
        attributes = [:name]
        devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
        devise_parameter_sanitizer.permit(:account_update, keys: attributes)
    end

    def after_sign_in_path_for(resource)
        posts_path(current_user) # your path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def new
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new
        
    end

    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.new(comment_params)
        if @comment.valid?
            @comment.save
            redirect_to post_path(@post)
        else
            render :new
        end
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end

    private

    def comment_params
        params.require(:comment).permit(:content, :post_id, :author_id)
    end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    before_action :set_user
  
    def follow_user
      if current_user.follow @user.id
        redirect_to @user
        end
    end
  
    def unfollow_user
        if current_user.unfollow @user.id
            redirect_to @user
        end
    end
  
    def followers
      @followers = @user.followers
    end
  
    def followees
      @followees = @user.followees
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = User.find(params[:id])
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    

    def index
        @user = User.all
        @posts = Post.all
        @post = Post.new
    end

    def most_recent
        @posts = Post.order(created_at: :desc)
    end

    def show
        @post = Post.find(params[:id])
        @comments = @post.comments
        @comment = Comment.new
    end

    def new
        @post = Post.new
    end

    def create
        @post = current_user.posts.new(post_params)
        if @post.valid?
            @post.save
            redirect_to posts_path
        else
            render new_post_path
        end
    end

    def edit
        @post = current_user.posts.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])
        @post.update(post_params)
        if @post.valid?
            @post.save
            redirect_to post_path(@post)
        else
            @error = @post.errors.full_messages
            render :edit
        end
    end

    def destroy
        @post = current_user.posts.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    private

    def post_params
        params.require(:post).permit(:content, :image_url, :views, :image)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
          sign_in_and_redirect @user
        else
          redirect_to new_user_registration_path
        end       
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show
        @user = User.find_by_id(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

    def index_date_format(post)
        created = post.created_at.to_datetime
        now = DateTime.now
        seconds = ((now - created) * 24 * 60 * 60).to_i
        minutes = seconds/60
        hours = minutes/60
        days = hours/24
        months = days/30
        years = months/12


        if seconds < 60
            return "#{seconds} seconds ago."
        elsif minutes < 60
            return "#{minutes} minutes ago."    
        elsif hours < 24
            return "#{hours} hours ago."
        elsif days < 30
            return "#{days} days ago."
        elsif months < 12
            return "#{months} months ago."
        else
            return "#{years} years ago."
        end

        
    end

    
end

app/helpers/users_helper.rb
module UsersHelper
    # Returns if the current user is following the user of passed in "following_id"
    def current_user_is_following(current_user_id, followee_id)
      follow_relationship = Follow.find_by(follower_id: current_user_id, followee_id: followee_id)
      return true if follow_relationship
    end
end

app/views/application/most_follows.html.erb
<h1>User with the most followers</h1><br>
<h2>Name: <%= @user_most_follows.name %></h2>
<h4>Followers: <%= @user_most_follows.followers.count %></h4>
<a href= <%= "/users/#{@user.id}" %>><h3><%= "Back to Account" %></h3></a>
<br>

app/views/application/search.html.erb
<h3>Search Result</h3>  

    <% @results.each do |result| %>  
        <%= result.content %>
        <%= image_tag result.image, style:'width:500px; height:500px; display: block' %>
    <% end %>

app/views/application/welcome.html.erb
<div class="container">
<h1>Welcome to RubySpace</h1></br>

<h2>The place where your social media is combined all into one place!<br><br> Please signup or Log in at the top</h2>

</div>

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.author.name %>:</strong>
          <%= comment.content %>
        </p>
      </div>
    </div>
    <% if user_signed_in? && comment.author == current_user %>
     <%= link_to 'Delete', [comment.post, comment],
                  method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
    <% end %>
  </article>
</div>

app/views/comments/_errors.html.erb
<% if @comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

            <ul>
            <% @comment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, @comment]) do |f| %>
    <div class="form-group">
    <%= f.hidden_field :author_id, value: current_user.id %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.text_area :content %>
    <%= f.submit :comment %>
    </div>
<% end %>

app/views/comments/new.html.erb
<%= render "errors" %>

<h1>Create new Comment for: </h1>
<h2><%= @post.content %></h2>
<br>


<%= render "form" %>

app/views/follows/followees.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-push-4 post">
    <h1>Listing @<%= @user.email %>'s Following</h1>
    <div class="row list_wrapper">
      <% @followees.each do |user| %>
        <a href= <%="/users/#{user.id}"%>>
          <div class="row list-head">
            <div class="col-xs-10 user-info">
              <h3>
                <strong> <%= user.email %> </strong><br>
                <small><strong> <%= user.name %> </strong></small>
              </h3>
            </div>
          </div>
        </a>
      <% end %>

      <div class="row">
        <div class="col-xs-12 link">
          <a href= <%= "/users/#{@user.id}" %>><h3><%= "Back to Account" %></h3></a>
        </div>
      </div>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 space">
  </div>
  <div class="col-xs-12 space">
  </div>
</div>

app/views/follows/followers.html.erb
<div class="row">
  <div class="col-xs-4 col-xs-push-4 post">
    <h3>Listing <%= @user.email %>'s Followers</h3>
    <div class="row list_wrapper">
      <% @followers.each do |user| %>
        <a href= <%="/users/#{user.id}"%>>
          <div class="row list-head">
            <div class="col-xs-10 user-info">
              <h3>
                <strong> <%= user.email %> </strong><br>
                <small><strong> <%= user.name %> </strong></small>
              </h3>
            </div>
          </div>
        </a>
      <% end %>

      <div class="row">
        <div class="col-xs-12 link">
          <a href= <%= "/users/#{@user.id}" %>><h3><%= "Back to Account" %></h3></a>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubySpace</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
    <%= stylesheet_link_tag "application.css" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <nav class="navbar navbar-expand-md navbar-light" style="background-color: #FFFFFF;" justify-content-between">
      <% if user_signed_in? %>
        <a class="navbar-brand" <%= link_to "RubySpace", posts_path, method: :get %></a>
      <% else %>
        <a class="navbar-brand" <%= link_to "RubySpace", root_path, method: :get %></a>
      <% end %>
          <div class="navbar-nav">
              <a class="nav-item nav-link active" </a>
              <% if user_signed_in? %>
                <a class="nav-item nav-link" <%= link_to "Account", current_user, method: :get %></a>
                <a class="nav-item nav-link" <%= link_to "Users", users_path, method: :get %></a>
                <a class="nav-item nav-link" <%= link_to "Posts", posts_path, method: :get %></a>
                <a class="nav-item nav-link" <%= link_to "Recent Posts", recent_path, method: :get %></a>
                <a class="nav-item nav-link" <%= link_to "Most Follows", most_follows_path, method: :get %></a>
                <a class="nav-item nav-link" <%= link_to "logout", destroy_user_session_path, method: :delete  %></a>
                <%= form_tag(search_page_path, :method => "get",   
                  class: 'navbar-form navbar-left') do %>  
                  <div class="input-group">  
                    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
                    <div class="input-group-btn">  
                    <%= button_tag "", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
                  </div>  
                </div>  
                <% end %>
              <% else %>
                <a class="nav-item nav-link" <%= link_to "Login", new_user_session_path, method: :get %></a>
                <a class="nav-item nav-link" <%= link_to "Signup", new_user_registration_path, method: :get %></a>
              <% end %>
            </div>
          </div>
    </nav>







    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
   
  
  <div class="wrapper">

    
    <%= yield %>

    <footer class="branding">
        <small>&copy; 2021 <strong>RubySpace by joshua burger</strong></small>
    </footer>

  </div>




  </body>
</html>

app/views/posts/_errors.html.erb
<% if @post.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post, :html => {:class => "form-horizontal center"} do |f| %>
    <div class="form-group">
            <div class="col-md-8">
            <%= f.text_area :content, class: "form-control", placeholder: "What would you like to post about?" %>
            <% if @post.image.attached? %>
                <%= image_tag @post.image, style:'width:500px; height:500px; display: block; border-radius: 20px;' %>
            <% end %>
            <%= f.label :image %>
            <%= f.file_field :image %>
            <%= f. submit class: 'btn btn-primary' %>
        </div>
    </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
    <h1>Edit your post</h1>
    <div class="card-deck">
        <div class="card align-items-center" style="width: 20rem;">
            <div class="card-block">
                <h2>Content: <%= @post.content %></h2><br>
                <%= render "form" %>
                <a class="nav-item nav-link btn btn-primary"<%= link_to "Back", post_path(@post) %>
            </div>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<% if user_signed_in? %>
    <h1>Welcome to RubySpace</h1>
    <h4>Below is a feed of all user's posts, Try making your own post!</h4><br>
    <div class="container">
        


        <%= render "form" %>


        <div>
            <ul><% @posts.each do |f| %>
                <div class="card-deck">
                    <div class="card align-items-center" style="width: 20rem;">
                        <div class="card-block">
                            <%= f.image_url %>
                            <%= f.views %>
                            <% if f.image.attached? %>
                                <%= link_to post_path(f) do %>
                                    <%= image_tag f.image, style:'width:500px; height:500px; display: block; border-radius: 20px;' %>
                                <% end %>
                            <% end %>
                            <p class="card-text">
                            <strong><h3><%= f.content %></h3></strong>
                            </p>
                            <div class="card-footer">
                                <%= index_date_format(f) %>
                                <a class="nav-item nav-link btn btn-primary"<%= link_to "View", post_path(f) %></a>
                                <% if user_signed_in? && f.user == current_user %>
                                <a class="nav-item nav-link btn btn-danger"<%= link_to "Delete", post_path(f), :method => "delete", data: { confirm: 'Are you sure?' } %></a>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
            </ul>
        </div>
    </div>
<% else %>
    <div class="container">
    <h1>Welcome to RubySpace</h1></br>

    <h2>The place where your social media is combined all into one place!<br><br> Please signup or Log in at the top</h2>

    </div>
<% end %>

app/views/posts/most_recent.html.erb
<h1> Most Recent </h1>

<div>
        <ul><% @posts.each do |f| %>
            <div class="card-deck">
                <div class="card align-items-center" style="width: 20rem;">
                    <div class="card-block">
                        <%= f.image_url %>
                        <%= f.views %>
                        <% if f.image.attached? %>
                            <%= link_to post_path(f) do %>
                                <%= image_tag f.image, style:'width:500px; height:500px; display: block; border-radius: 20px;' %>
                            <% end %>
                        <% end %>
                        <p class="card-text">
                        <strong><h3><%= f.content %></h3></strong>
                        </p>
                        <div class="card-footer">
                            <%= index_date_format(f) %>
                            <a class="nav-item nav-link btn btn-primary"<%= link_to "View", post_path(f) %></a>
                            <% if user_signed_in? && f.user == current_user %>
                            <a class="nav-item nav-link btn btn-danger"<%= link_to "Delete", post_path(f), :method => "delete", data: { confirm: 'Are you sure?' } %></a>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
        </ul>
    </div>
</div>

app/views/posts/new.html.erb
<%= render "errors" %>


<div class="container">
    <h1>Create a new post</h1>
    <%= render "form" %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <h2>User: <%= @post.user.name %><br></h2><%= link_to "Profile", user_path(@post.user.id) %>
  <div class="card-deck">
    <div class="card align-items-center" style="width: 20rem;">
      <div class="card-block">
      <% if @post.image.attached? %>
          <p>
            <%= image_tag @post.image, style:'width:500px; height:500px; display: block; border-radius: 20px;' %>
          </p>
        <% end %>
        <h2><%= @post.content %></h2><br>
        <a class="nav-item nav-link btn btn-primary"<%= link_to "Add a new comment", new_post_comment_path(@post) %></a>
        <ul>
            <h3><span class="tag is-rounded"><%= @post.comments.count %> comments</span></h3><br>
            <%= render @comments %>
        </ul>
        <% if user_signed_in? && @post.user == current_user %>
        <div class="card-footer">
        <a class="nav-item nav-link btn btn-warning"<%= link_to "Edit", edit_post_path(@post) %></a>
        <% end %>
        <a class="nav-item nav-link btn btn-primary"<%= link_to "Back", posts_path(@post) %></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_userposts.html.erb
<% @user.posts.each do |post| %>
    <div class="card-deck">
        <div class="card align-items-center" style="width: 20rem;">
            <div class="card-block">
                <%= post.image_url %>
                <%= post.views %>
                <% if post.image.attached? %>
                    <%= link_to post_path(post) do %>
                        <%= image_tag post.image, style:'width:500px; height:500px; display: block; border-radius: 20px;' %>
                    <% end %>
                <% end %>
                <p class="card-text">
                <strong><h3><%= post.content %></h3></strong>
                </p>
                <div class="card-footer">
                    <%= index_date_format(post) %>
                    <a class="nav-item nav-link btn btn-primary"<%= link_to "View", post_path(post) %></a>
                    <% if user_signed_in? && post.user == current_user %>
                    <a class="nav-item nav-link btn btn-danger"<%= link_to "Delete", post_path(post), :method => "delete" %></a>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-xs-4 col-xs-push-4 post">
    <h1>Listing Users</h1>

    <div class="row list_wrapper">
      <% @users.each do |user| %>
        <a href= <%="/users/#{user.id}"%>>
          <div class="row list-head">
            <div class="col-xs-10 user-info">
              <h3>
                <strong> <%= user.email %> </strong><br>
                <small><strong> <%= user.name %> </strong></small>
              </h3>
            </div>
          </div>
        </a>
      <% end %>

      <div class="row">
        <div class="col-xs-12 link">
          <a href="/posts"><h3>Return to Home</h3></a>
        </div>
      </div>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-12 space">
  </div>
  <div class="col-xs-12 space">
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-push-2">
    <p id="notice"><%= notice %></p>
  </div>
</div>

<div class="container-fluid">
  <div class="row about">
    <div class="col-xs-6 col-xs-push-2">
      <div class="row">
        <div class="col-xs-12 about">
          <% if @user == current_user %>
            <h2><strong>Welcome to your account</strong></h2><br>
          <% else %>
            <h2><strong>Welcome to <%= @user.name %>'s account</strong></h2><br>
            <% end %>
          <p>
            <span style="font-size:30px">
              <%= @user.email %><br>
            </span>
            <h3><strong>Posts: <%= @user.posts.count %></strong></h3><br>
            <a href=<%= "/users/#{@user.id}/followers" %>>
              <strong>Followers:</strong>
              <%= "#{@user.followers.count}" %>
            </a><br><br>
            <a href=<%= "/users/#{@user.id}/following" %>>
              <strong>Following:</strong>
              <%= "#{@user.followees.count}" %><br>
            </a><br>
          </p>

          <% if user_signed_in? %>
            <div class="row">
              <% if @user == current_user %>
                <a class="nav-item nav-link btn btn-primary"<%= link_to 'New Post', '/posts' %>
              <% elsif current_user_is_following(current_user.id, @user.id) %>
                <a class="nav-item nav-link btn btn-danger"<%= link_to 'Unfollow', "/users/#{@user.id}/unfollow_user", method: :post %>
              <% else %>
                <a class="nav-item nav-link btn btn-primary"<%= link_to 'Follow', "/users/#{@user.id}/follow_user", method: :post %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-8 col-xs-push-2">
    <div class="row">
        <% if @user.posts.count == 0 %>
          <div class="col-xs-12 no-posts">
            <% if @user.name.empty? %>
              <h2><%=@user.name%> has no posts yet :(</h2>
            <% else %>
              <h2><%=@user.name%> has no posts yet :(</h2>
            <% end %>
          </div>
        <% elsif %>
          <% if current_user_is_following(current_user.id, @user.id) %>
              <%= render "userposts" %>
          <% else %>
            <% if @user == current_user %>
              <h1>My account</h1>
              <%= render "userposts" %>
            <% else %>
              <h1>Follow if you want to see my posts!</h1>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    </div>
  </div>
</div>